### ISSUE TITLE
Attempting to add values to wod rolls returns error

### ISSUE THREAD

**Issue by SheWhoSpeaksInSighs** [Humblemonk/dicemaiden-rs#2]
Title, possibly an oversight as this wasn't an issue in the prior version. 

Attempting to write a command like "/r 10wod6+2" now returns an error, when before it would simply roll as normal, then add +2 to the success count.

**Comment by Humblemonk** [comment]
Hey! First issue for the new version of the bot :) Thanks for submitting! I will look into it asap

**Comment by Humblemonk** [comment]
I think I fixed this. It should be going live within the hour. Let me know! Thanks

**Comment by SheWhoSpeaksInSighs** [comment]
Partially! Doesn't return an error now, but it still doesn't add to the successes.

**Comment by Humblemonk** [comment]
Thanks for the feedback. I will investigate and see what else I can do here with the regex syntax
